### ISSUE TITLE
running `docker-compose up -d`  only shows up the gateone terminal

### ISSUE THREAD

**Issue by oz123** [arush-sal/cka-practice-environment#10]
I can't see any of the exercises, is this expected?

**Comment by cristian04** [comment]
Are you opening localhost or localhost:8080?

**Comment by oz123** [comment]
I opened http://localhost:8080, in localhost it's available.

**Comment by cristian04** [comment]
Localhost has the exams + an iframe pointing to the lab terminal (8080) 

This is working as expected.

**Comment by oz123** [comment]
Yes. That was unclear from the docs
