### ISSUE TITLE
"audit policy" dead link 

### ISSUE THREAD

**Issue by yogeek** [arush-sal/cka-practice-environment#3]
The following question contains a dead link :

> Q. Enable cluster auditing
> Enable cluster wide auditing. You can use the audit policy provide at [here](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/debug-application-cluster/audit-policy.yaml).
> Make sure the audit logs are properly generated and saved to a log file.

**Comment by arush-sal** [comment]
Could please also let me know which question number is this?
