### ISSUE TITLE
Boostraping not clear

### ISSUE THREAD

**Issue by yogeek** [arush-sal/cka-practice-environment#4]
In the 1st question : "Bootstrap a Kubernetes v1.10 cluster using kubeadm", it seems that kubeadm is not installed and even docker daemon is not running in the SSH Terminal : is it normal ? 
Do we need to install all the needed tools manually in the web app console before taking the test ?

**Comment by arush-sal** [comment]
No, in the exam you don't need to install all the tools needed manually but rather it all will be provided. I tried working on a similar setup as play-with-k8s but could get it working and didn't have much time to work on it after that. Therefore yes, it is far from perfect and a lot of things needs to be fixed here before we can call it stable.

**Comment by yogeek** [comment]
Ok thanks. I will look into this and make a PR if I find the time :-)
